version: '3.5'

services:
  taigi_susing:
    image: i3thuan5/taigi_susing
    command: gunicorn -w 2 -b 0.0.0.0:5000 --log-level debug 標詞性:app
    expose:
      - 5000
    networks:
      - default
      - nginx-bridge
    environment:
      VIRTUAL_HOST: "xn--s-sng-vsa6h.xn--v0qr21b.xn--kpry57d"
      VIRTUAL_PORT: 5000
    restart: always

networks:
  nginx-bridge:
    external: true

