version: '3.5'

services:
  taigi_susing:
    image: i3thuan5/taigi_susing
    command: bash -c "sed 's/<bun5ji7>/<path:bun5ji7>/g' -i 標詞性.py && gunicorn -w 1 -t 4 -b 0.0.0.0:5000 --log-level debug 標詞性:app"
    expose:
      - 5000
    networks:
      - default
      - nginx-bridge
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST:-susing.ithuan.tw}"
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: "${VIRTUAL_HOST:-susing.ithuan.tw}"
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always

networks:
  nginx-bridge:
    external: true

